=== deepakbhalla/jax-ws-soap-web-services/XMLSchemaToXML/Employee.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.deepakbhalla.com/Employee"
	xmlns:tns="http://www.deepakbhalla.com/Employee" elementFormDefault="qualified">

	<!-- elementFormDefault="qualified" signifies that all the elemnts in xml 
		file corresponding to this xsd should have namespaces. However elementFormDefault="unqualified" 
		signifies that namespace is not required in the elements of xml file -->

	<!-- Please note: This file has been created manually -->

	<element name="Employee" type="tns:Employee" />

	<complexType name="Employee">
		<!-- By default all the elements in <sequence> element should be present 
			in xml. To control the min and max occrances of the elements in xml, minOccors 
			and maxOccurs can be used -->
		<sequence>
			<element name="id" type="tns:ID" />
			<element name="name" type="tns:String15Length" />
			<element name="age" type="string" />
			<element name="email" type="string" />
			<element name="dob" type="string" />
			<element name="gender" type="tns:GENDER" />
			<element name="phone" type="int" minOccurs="0" maxOccurs="2" />
			<element name="paymentType" type="tns:PaymentType" />
		</sequence>

		<!-- Used to declare definition of any attribute to be present in this 
			complex type attributes. Please notice 'sampleAttribute' attribute present 
			in 'tns:Employee' in generated xml file -->
		<attribute name="sampleAttribute" type="string" />

	</complexType>

	<complexType name="PaymentType">
		<choice>
			<element name="cash" type="int" />
			<element name="insurance" type="tns:insurance" />
		</choice>
	</complexType>

	<complexType name="insurance">
		<!-- Order or elements doesn't matter in <all> element -->
		<all>
			<element name="provider" type="string" />
			<element name="limit" type="int" />
		</all>
	</complexType>

	<simpleType name="ID">
		<restriction base="int">
			<pattern value="[0-9]*" />
		</restriction>
	</simpleType>

	<simpleType name="String15Length">
		<restriction base="string">
			<maxLength value="15" />
		</restriction>
	</simpleType>

	<simpleType name="GENDER">
		<restriction base="string">
			<enumeration value="M" />
			<enumeration value="F" />
		</restriction>
	</simpleType>

</schema>

=== deepakbhalla/jax-ws-soap-web-services/XMLSchemaToXML/Employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Employee xmlns:tns="http://www.deepakbhalla.com/Employee"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.deepakbhalla.com/Employee Employee.xsd"
	sampleAttribute="samlpeValue">

	<!-- Please note: This file has been generated by using Eclipse IDE by referring 
		to the Employee.xsd file -->

	<tns:id>12345</tns:id>
	<tns:name>tns:name</tns:name>
	<tns:age>tns:age</tns:age>
	<tns:email>tns:email</tns:email>
	<tns:dob>tns:dob</tns:dob>
	<tns:gender>M</tns:gender>
	<tns:phone>56789</tns:phone>
	<tns:phone>56123</tns:phone>
	<tns:paymentType>
		<tns:insurance>
			<tns:limit>12345</tns:limit>
			<tns:provider>ABCD</tns:provider>
		</tns:insurance>
	</tns:paymentType>

</tns:Employee>
